### PR TITLE
Fix #96, optimize getPlotMid

### LINKED ISSUE #96: PlotMid is wrong
TODO for myself, i'll PR soon:

https://github.com/jasonwynn10/MyPlot/blob/API3/src/MyPlot/MyPlot.php#L418
does nothing. add returns a new Vector3, its not assigned to pos
the lines after are useless too. the mid is always x + half, y + half

### PR DESCRIPTION
**Pull request by thebigsmileXD**
- [x] This PR actually submits something - don't use this system as a messaging service!
- [x] This PR isn't duplicated - you can check if it is by scanning the small list - link is on the navigation bar for this repository.
- [x] This PR includes appropriate markdown for sections - e.g. code blocks for suggested code.
- [x] This PR description and comments in code is understandable - feel free to use your native language to write if you are not comfortable with English.
- [x] This PR has a single branch for itself in your fork - don't just commit to the master branch of your repository!
- [x] This PR has comments written in clear English - please don't write unreadable comments just for your eyes.

## Pull Request description
This PR is a Fix for #96 
- Fix position
- Respect actual mid (+0.5 if uneven plotsize) -> you spawn in the exact center

## Optional information
{Type something here}

### CODE REVIEW

File: src/MyPlot/MyPlot.php [hunk 1]
```diff
@@ -414,14 +414,7 @@ public function getPlotMid(Plot $plot) {
...
 		$pos = $this->getPlotPosition($plot);
-		if($plot->X >= 0 and $plot->Z >= 0)
-			$pos->add(floor($plotSize / 2), 1, floor($plotSize / 2));
-		if($plot->X < 0 and $plot->Z > 0)
-			$pos->add(-floor($plotSize / 2), 1, floor($plotSize / 2));
-		if($plot->X > 0 and $plot->Z < 0)
-			$pos->add(floor($plotSize / 2), 1, -floor($plotSize / 2));
-		if($plot->X < 0 and $plot->Z < 0)
-			$pos->add(-floor($plotSize / 2), 1, -floor($plotSize / 2));
+		$pos = new Position($pos->getFloorX() + ($plotSize / 2) + 0.5, $pos->getFloorY() + 1, $pos->getFloorZ() + ($plotSize / 2) + 0.5);
```
Comment (jasonwynn10) [inline src/MyPlot/MyPlot.php]: Are you certain that this returns the exact center every time? It doesn't really account for positive or negative x/z coords

Comment (thebigsmileXD) [inline src/MyPlot/MyPlot.php]: It does - whoever got the stupid idea that plot positions return the distance from x0;z0 instead of the plot position didn't learn well about coordinates in math.

Comment (thebigsmileXD) [inline src/MyPlot/MyPlot.php]: image
Maybe this image explains it. the position of the plot is always at the lowest x/z

Comment (jasonwynn10) [reply src/MyPlot/MyPlot.php]: I'm testing now

Comment (jasonwynn10) [reply src/MyPlot/MyPlot.php]: Have you tested this?

Comment (thebigsmileXD) [reply src/MyPlot/MyPlot.php]: Would i create untested PR's? ;) Sure i did. Was my explaination above understandable? I wanted to say that: the plotpos is always the lowest x and z of a plots area. in order to get the middle, you would always have to go to the positive direction. Also, currently it just teleports to the plotpos because the position doesn't get changed in the code anyways
